[package]
name = "aoc-01-fuel-consumption"
version = "0.1.0"
authors = ["Roman Decker <roman.decker@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
